
<div style="float:left; verticle-align: top;" >
<h1>Unsere Elefanten</h1>

<object width="300"><param name="movie" value="http://www.youtube.com/v/g-QIbqW3ugk&hl=de_DE&fs=1&"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/g-QIbqW3ugk&hl=de_DE&autoplay=1&" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="300"></embed></object>
</div>

<div> 
<h1>und unsere Tiger</h1>


<object width="300"><param name="movie" value="http://www.youtube.com/v/asqHco-jbWk&hl=de_DE&fs=1&"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/asqHco-jbWk&hl=de_DE&autoplay=1&" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="300"></embed></object>
</div>
