<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="de" lang="de">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <title>Zoo Mannheim</title>

    <meta name="author-personal" content="Martin Kapfhammer" />
    <meta name="author-mail" content="mailto:martin.kapfhammer@gmx.net" />

    <meta name="language" content="de" />

	<?php 
		$style = (isset($_COOKIE['style'])) ? $_COOKIE['style'] : 'style';
		$available_styles = array('style', 'blue');
		if (!in_array($style, $available_styles)) $style = 'style';
		$link  = '/css/' . $style . '.css';
    	echo $this->headLink()->appendStylesheet($link); 
	?>
	<?php echo $this->headLink()->appendStylesheet('/css/formular.css'); ?>
  </head>
  <body id="container">
	<div id="header">
		<img src="<?php echo $this->baseUrl . '/img/header.jpg'; ?>">
	</div>
	<?php $link = str_replace('/', '_', getenv('REQUEST_URI')); ?>
	<a href="/index/index/style/style/back/<?php echo $link; ?>">Standard</a>
	<a href="/index/index/style/blue/back/<?php echo $link; ?>">Blau</a>
	<div id="login">
		<div id="login1">

			<a href="<?php echo $this->baseUrl . '/index'; ?>">Start</a>
			<a href="<?php echo $this->baseUrl . '/game'; ?>">Das Spiel</a>
			<a href="<?php echo $this->baseUrl . '/images'; ?>">Bilder</a>
			<a href="<?php echo $this->baseUrl . '/shop'; ?>">Shop</a>
		</div>
		<div id="login2" align="right">
			<?php
			if (Zend_Auth::getInstance()->hasIdentity()) {
			$userSession = new Zend_Session_Namespace('user');
			$user 		 = $userSession->user;
			$name    	 = $user['firstname'] . ' ' . $user['lastname'];
			$link = "/user/logout";
			$text = "Logout";
			echo 'Herzlich Willkommen ' . $name . '   &raquo;'; 
			} else {
				$link = "/user/login";	
				$text = "Login";
			}
			echo '<a href="' . $this->baseUrl().$link; 
			?>">
		<?php echo $text ?></a>
		</div>
	</div>
	<div id="navi">
		<br />
		<br />
		<br />
		
		<h3>Allgemein</h3>
		<ul>
			<li><a href="<?php echo $this->baseUrl . '/index'; ?>">Start</a></li>
			<li><a href="<?php echo $this->baseUrl . '/booking'; ?>">Tickets</a></li>
			<br />
			<br />
		</ul>
		<h3>Interaktiv</h3>
		<ul>
			<li><a href="<?php echo $this->baseUrl . '/webcam'; ?>">Zoo Webcam</a></li>
			<li><a href="<?php echo $this->baseUrl . '/survey'; ?>">Umfrage</a></li>
			<li><a href="<?php echo $this->baseUrl . '/game'; ?>">Spiel</a></li>
			
			<br />
			<br />
		</ul>
		<h3>Community</h3>
		<ul>
			<li><a href="<?php echo $this->baseUrl . '/community'; ?>">Die Zoo-Community</a></li>
			<li><a href="<?php echo $this->baseUrl . '/'; ?>">Gästebuch</a></li>
			<br />
			<br />
		</ul>
		<?php if (Zend_Auth::getInstance()->hasIdentity()): ?>

		<h3>Privat</h3>
		<ul>
			<li><a href="<?php echo $this->baseUrl . '/user/profile'; ?>">Profil</a></li>
			<li><a href="<?php echo $this->baseUrl . '/community/friends'; ?>">Meine Freunde</a></li>
			<li><a href="<?php echo $this->baseUrl . '/community/showmessages'; ?>">Neue Nachrichten [<?php echo $this->unreadMessages; ?>]</a></li>

		</ul>
		<?php endif; ?>
	</div>

	<div id="content">
		<?php echo $this->layout()->content; ?>
	</div>

	<div id="footer" align="right">
		Hier kommt irgendein Text hin
	</div>

  </body>
</html>

