<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="de" lang="de">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <title>Zoo Mannheim</title>

    <meta name="author-personal" content="Martin Kapfhammer" />
    <meta name="author-mail" content="mailto:martin.kapfhammer@gmx.net" />

    <meta name="language" content="de" />

    <?php echo $this->headLink()->appendStylesheet('/css/style.css'); ?>
  </head>
  <body id="container">
	<div id="header">
		<h1>Zoo Mannheim</h1>
	</div>
	<div id="login">
			<?php
			if (Zend_Auth::getInstance()->hasIdentity()) {
				$userSession = new Zend_Session_Namespace('user');
				$user 		 = $userSession->user;
				$name    	 = $user['firstname'] . ' ' . $user['lastname'];
				$link = "/user/logout";
				$text = "Logout";
				echo 'Herzlich Willkommen ' . $name . '   &raquo;';
			} else {
				$link = "/user/login";	
				$text = "Login";
			}
			echo '<a href="' . $this->baseUrl().$link; 
			?>
			"><?php echo $text ?></a>
	</div>
	
	<div id="navi">
	</div>

	<div id="content">
		<?php echo $this->layout()->content; ?>
	</div>

	<div id="footer"></div>

  </body>
</html>

