<div id="showmessage">
	<h1>Meine privaten Nachrichten</h1>
	<br />
	<br />
	<?php if (!empty($this->messages)): ?>
		<?php foreach($this->messages as $message): ?>
			<table>
				<tr>
					<th><?php echo $message['fullname']; ?></th>
					<th align="right"><?php echo $message['subject']; ?></th>
				</tr>
				<tr>
					<td id="date"><?php echo $message['date']; ?></td>
				</tr>
				<tr>
					<td><?php echo $message['message']; ?></td>
				</tr>
			</table>
			<h3><a href="<?php echo $this->baseUrl . '/community/message/to/' . $message['from']['userid']; ?>">Antworten</a></h3>
			<br />
			<br />
		<?php endforeach; ?>
	<?php else: ?>
		<h3>Keine Nachrichten vorhanden</h3>
	<?php endif; ?>




	<br />
	<br />

	<table id="privmessage">
		<tr>
			<td><a href="<?php echo $this->baseUrl . '/user/profile'; ?>"><< Zurück zum Profil</a></td>
			<td><a href="<?php echo $this->baseUrl . '/community/showsendmessages'; ?>">Meine gesendeten Nachrichten</a></td>
		</tr>
	</table>
	

</div>
