<script type="text/javascript" src="/js/3rdParty/jQuery.js"></script>
<script type="text/javascript" src="/js/3rdParty/jquery.validate.js"></script>
<script type="text/javascript" src="/js/register.js"></script>

<h1>Passwort ändern</h1>
<br />
<br />
<br />
<?php if ($this->success === true): ?>
	<div class="success">
		<p>Änderungen gespeichert.</p>
	</div>
<?php endif; ?>


<?php if (!empty($this->errors)): ?>
	<div class="error">
		<ul>
			<?php foreach($this->errors as $error): ?>
				<li><?php echo $error; ?></li>
			<?php endforeach; ?>
		</ul>
	</div>
<?php endif; ?>


<?php echo $this->form; ?>

<a href="<?php echo $this->baseUrl . '/user/profile'; ?>">Zurück zum Profil</a>
