<script type="text/javascript" src="/js/3rdParty/jQuery.js"></script>
<script type="text/javascript" src="/js/3rdParty/jquery.validate.js"></script>
<script type="text/javascript" src="/js/register.js"></script>

<h1>Passwort ändern</h1>

<?php if ($this->success === true): ?>
	<p>Änderungen gespeichert.</p>
<?php endif; ?>


<?php if (!empty($this->errors)): ?>
<ul>
    <?php foreach($this->errors as $error): ?>
        <li><?php echo $error; ?></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>


<?php echo $this->form; ?>

<a href="<?php echo $this->baseUrl . '/user/profile'; ?>">Zurück zum Profil</a>
