
<script type="text/javascript" src="/js/3rdParty/jQuery.js"></script>
<script type="text/javascript" src="/js/editprivate.js"></script>
<h1>Persönliche Angabe bearbeiten</h1>


<br />
<br />

<?php echo $this->form; ?>

<?php if (isset($this->success)): ?>

	<div class="success">
		<?php echo $this->success; ?>
	</div>
<?php endif; ?>

<br />
<br />
<a id="privmessage" href="<?php echo $this->baseUrl . '/user/profile'; ?>"><< Zurück zum Profil</a>
