<?php echo $this->headLink()->appendStylesheet('/css/3rdParty/jquery.ui.css'); ?>
<script type="text/javascript" src="/js/3rdParty/jQuery.js"></script>
<script type="text/javascript" src="/js/3rdParty/date.js"></script>
<script type="text/javascript" src="/js/3rdParty/jquery.ui.js"></script>
<script type="text/javascript" src="/js/3rdParty/jquery.datePicker.js"></script>
<script type="text/javascript" src="/js/editaddress.js"></script>


<h1>Adressdaten bearbeiten</h1>

<?php if ($this->success === true): ?>
	<p>Änderungen gespeichert.</p>
<?php endif; ?>


<?php if (!empty($this->errors)): ?>
<ul>
    <?php foreach($this->errors as $error): ?>
        <li><?php echo $error; ?></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>

<?php echo $this->form; ?>

<a href="<?php echo $this->baseUrl . '/user/profile'; ?>">Zurück zum Profil</a>
