
<?php if ($this->success === true): ?>
	<div class="success">
		<p>Änderungen gespeichert.</p>
	</div>
<?php endif; ?>

<?php if (!empty($this->errors)): ?>
	<div class="error">
		<ul>
			<?php foreach($this->errors as $error): ?>
				<li><?php echo $error; ?></li>
			<?php endforeach; ?>
		</ul>
	</div>
<?php endif; ?>

<?php echo $this->form; ?>

<a href="<?php echo $this->baseUrl . '/user/profile'; ?>">Zurück zum Profil</a>
