<script type="text/javascript" src="/js/3rdParty/jQuery.js"></script>
<script type="text/javascript" src="/js/3rdParty/jquery.validate.js"></script>
<script type="text/javascript" src="/js/register.js"></script>

<h1>Registrierung</h1>

<?php if ($this->success === true): ?>
	<p>Herzlichen Glückwunsch! Sie wurden erfolgreich registriert. Hier können Sie sich nun 
		<a href="<?php echo $this->baseUrl. '/user/login'; ?>">einloggen</a>.
	</p>
<?php endif; ?>


<?php if (!empty($this->errors)): ?>
<ul>
    <?php foreach($this->errors as $error): ?>
        <li><?php echo $error; ?></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>


<?php echo $this->form; ?>

